---
- name: Launch application container
  docker_container:
    name: my-front
    image: alexisp1909/tp-devops-front  # Replace with your actual app image
    pull: always
    state: started
    restart_policy: unless-stopped
    ports: "90:90"
    networks:
      - name: my_network
