---
# tasks file for launch-database

- name: Launch PostgreSQL database container
  docker_container:
    name: my-db
    image: alexisp1909/tp-devops-database
    pull: yes
    published_ports:
      - "5432:5432"
    networks:
      - name: my_network    
    env:
      POSTGRES_DB: db 
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: pwd
    state: started  # Ensure the container is started
    restart_policy: unless-stopped  # Optional, but good practice
