name: Build and Push Docker Image
on:
  workflow_run:
    workflows: ["Test Backend"]
    types:
      - completed
  push:
      branches:
        - main
  pull_request:
      branches:
        - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
              # relative path to the place where source code with Dockerfile is located
              context: ./simple-api
              # Note: tags has to be all lower-case
              tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
              push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
           context: ./database
           tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest
           push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
            context: ./http-server
            tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-http-server:latest
            push: ${{ github.ref == 'refs/heads/main' }}
